name: Node.js CI

on:
  push:
    branches:  main 

jobs:
  publish:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps: 
    - uses: actions/checkout@v2
    - name: Use Node.js 18.x
      uses: actions/setup-node@v2
      with:
        node-version: 18.x
    - run: npm ci
    - run: npm run semantic-release
      env: 
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
